name = "Runestones"
author = "Ifiht"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2586e2cd8b76826c9cf681bea517a590fc67a8355dc5cc8c703062ed2f87f24"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
