name = "Runestones"
author = "Ifiht"
version = "2.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c039086f0408867d31d53790230f3afb7c4f0d8ff2ac11a8c7db0a2790950390"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
