name = "Runestones"
author = "Ifiht"
version = "3.1.7"
description = "Client modpack for Ithavollr"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faf74af556207bf341be079e64d77f9fcc5aeaa393cbfb64ad564d9b87e0b7fe"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
