name = "Runestones"
author = "Ifiht"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9bd9d3d50b2a7f091ab3ced994d9f223641bdd4f3047d85183bd3262d6dbc2f"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
