name = "Runestones"
author = "Ifiht"
version = "3.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5a9f7f8eee39378b28282e6c102d2082589d0a65bdb462075e4a4a86c1ae9d2"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
