name = "Runestones"
author = "Ifiht"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89929da6eac60b8ac19de14763c293bbe6a71edb3d27175159cc6ef859ab2009"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
