name = "Runestones"
author = "Ifiht"
version = "2.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e22a631f2c155adcafaa8d44bdedb7f3b9e134516feb709b001f7408a4eb697a"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
