name = "Runestones"
author = "Ifiht"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86b99e610ba55427a2496c0da7ebaf685bd08e493cac173af56ace83c7194ec1"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
