name = "Runestones"
author = "Ifiht"
version = "2.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e39cc855cd8ae320b8c031cec9e717490a26fb41f1aae8fa25cb4c678bdfe4e6"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
