name = "Runestones"
author = "Ifiht"
version = "3.1.4"
description = "Client modpack for Ithavollr"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bccb9ba50a3405d938413150c044e669a194104fb662683735d3c9e1d75486b4"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
