name = "Runestones"
author = "Ifiht"
version = "3.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4e22ce1f01b657dcc1dcdb84431216260ff3bb5b71e69922ac36494da5756c7"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
