name = "Runestones"
author = "Ifiht"
version = "2.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe8a7ea28133deeb3d42a5b665f8da0aba17fe09f60698a3c7cbb10d240b0421"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
