name = "Runestones"
author = "Ifiht"
version = "2.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "797f4a44c6a4b6f390f00e8c359cd6fab2a2887e114a1345197e4cabb685980a"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
