name = "Runestones"
author = "Ifiht"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adb7cb4151d656b67db6d722384ae0cbc82f06de1b1fc300549896a19186a8f0"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
