name = "Runestones"
author = "Ifiht"
version = "3.1.7"
description = "Client modpack for Ithavollr"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f90fe6719e6177a5977fddbb834bd2a821fc0559cda8fe0192ba94b292c9a6c8"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
