name = "Runestones"
author = "Ifiht"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b633a2680c1a083a000bc688f548307fc7c4446700db0efc55794d5218bca0df"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
