name = "Runestones"
author = "Ifiht"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce065bab164ec47b7087ac0fd42bdc0884abc254e500a1328a915f9d2c597ff1"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
