name = "Runestones"
author = "Ifiht"
version = "3.2.0"
description = "Client modpack for Ithavollr"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ddeea10bdc69425339f49e62b826bcc15bba0b7976afdd33505b44e3feeb1c7"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
