name = "Runestones"
author = "Ifiht"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d0b744d94539c8aca2cf3c2ac5e6de842e0ec312a84d0e1fee710fb566ff656"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
