name = "Runestones"
author = "Ifiht"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fd83dbe63071b282acd9c0a29d0344e2ca39bbd21c6f51ebbc0938ea9b92d80"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
