name = "Runestones"
author = "Ifiht"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1a7ea29227ccea1eebd9d009d60c4532730d4def3a722e75734424c6ec5c4a6"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
