name = "Runestones"
author = "Ifiht"
version = "2.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fa905ffea111bbfe26e0e1d104e54b32ca0775b8e0dc7487693d23bb63283ff"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
