name = "Runestones"
author = "Ifiht"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c116887ee7b3b3115c16f93f35f34d7f45d994a951a0867df178fdee73f172f8"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
