name = "Runestones"
author = "Ifiht"
version = "3.1.3"
description = "Client modpack for Ithavollr"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d462bc4506ef7272f0e4e2408c58939c2b78124c7f46f404230ae0ad797eee71"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
